### ISSUE TITLE
Hide on taskbar doesn't work

### ISSUE THREAD

**Issue by Fossibaer** [BlueBird67/BlackScreens#3]
I'm using Black Screens 1.12 on my Windows 10. The new function that minimizes the program to the tray bar only after starting doesn't work. The properties window is always displayed.

**Comment by BlueBird67** [comment]
Please try this new [1.13 release](https://github.com/BlueBird67/BlackScreens/releases/tag/1.13). Uninstall old version before installing this new one.

Be aware that old preferences will be reset on first launch.

Let me know if it's working as expected.

**Comment by Fossibaer** [comment]
The 1.13 works. Thanks.

**Comment by BlueBird67** [comment]
Great news! Thanks for using the app.
I've just seen that there is a new bug with first screen name shown on first BlackScreen, I will dig in. This mean a new version should come this week.
